name: Invoice Ninja
version: 1.0.5
slug: invoiceninja
description: Invoice Ninja for Home Assistant
url: https://github.com/Nephilim293/invoiceninja-ha
arch:
  - aarch64
  - amd64

init: false
ingress: true
ingress_port: 8080
ingress_entry: /
panel_icon: mdi:file-document
panel_title: Invoice Ninja

ports:
  8080/tcp: 8080

hassio_api: true

options:
  app_key: ''
  db_host: 'core-mariadb'
  db_port: '3306'
  db_database: 'ninja'
  db_username: 'ninja'
  db_password: 'changeme'

schema:
  app_key: str
  db_host: str
  db_port: str
  db_database: str
  db_username: str
  db_password: str
